#!/bin/bash 
sleep $[ ( $RANDOM % 1800 )  + 1 ]s
r=$(( $RANDOM % 298 )); echo $r
cd /home/pi/rabbit
omxplayer /home/pi/rabbit/us/$r.mp3

sleep $[ ( $RANDOM % 1800 )  + 1 ]s
r=$(( $RANDOM % 302 )); echo $r
cd /home/pi/rabbit
omxplayer /home/pi/rabbit/uk/$r.mp3

